### ISSUE TITLE
Git export failure - user nlvs01

### ISSUE THREAD

**Issue by julianghionoiu** [julianghionoiu/dev-sourcecode-record#25]
The following sourcecode recording fails the export command with an IndexOutOfBoundsException:
https://s3.eu-west-2.amazonaws.com/tdl-official-videos/CHK/nlvs01/sourcecode_20180811T125110.srcs

command
```
 java -jar dev-sourcecode-record-0.0.15-all.jar convert-to-git -i sourcecode_20180811T125110.srcs -o to_git
```

output:
```
Committing timestamp: 3149
Exception in thread "main" java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 50, Size: 50
	at tdl.record.sourcecode.ConvertToGitCommand.run(ConvertToGitCommand.java:45)
	at tdl.record.sourcecode.App.main(App.java:27)
```

Needs to be investigated

**Comment by julianghionoiu** [comment]
Might be related to https://github.com/julianghionoiu/dev-sourcecode-record/issues/24

**Comment by neomatrix369** [comment]
@julianghionoiu 
Looking at this issue, narrowed it down to this block (see https://github.com/julianghionoiu/dev-sourcecode-record/blob/master/src/main/java/jgit/hack/ApplyCommandFixed.java#L181):

```java
            for (int j = 1; j < hunkLines.size(); j++) {
                String hunkLine = hunkLines.get(j);
                switch (hunkLine.charAt(0)) {
                    case ' ':
                        ensureLineContentMatchesDestination(hunkLine.substring(1), newLines, hh, pos);
                        pos++;    <=== incremented when ' ' is encountered
                        break;
                    case '-':
                        if (hh.getNewStartLine() == 0) {
                            newLines.clear();
                        } else {
                            ensureLineContentMatchesDestination(hunkLine.substring(1), newLines, hh, pos);
                            newLines.remove(hh.getNewStartLine() - 1 + pos);  <=== failing here like it says java.lang.IndexOutOfBoundsException: Index: 50, Size: 50 i.e. newLines.size() at that time is 50 and hh.getNewStartLine() - 1 + pos is evaluting to 50, and HunkHeader[48,4->48,3]
                        }
                        <=== should pos be decremented when '-' is encountered?
                        break;
                    case '+':
                        newLines.add(hh.getNewStartLine() - 1 + pos,
                                hunkLine.substring(1)); 
                        pos++;   <=== incremented when '+' is encountered
                        break;
                }
            }
        }
```
Left a question for case '-', the `pos` value is going out of sync when `hunkLine.charAt(0)` encounters combinations of ' ' and '+' ;

Please also explain what each of the blocks against ' ', '+' and '-' do, saves me from assuming what the code is doing or suppose to do.

Also how do you translate this `HunkHeader[48,4->48,3]`?

**Comment by neomatrix369** [comment]
Nature of the issue is similar to #24

**Comment by julianghionoiu** [comment]
That code is supposed to apply a patch and the symbols mean:
-  ' ' - line stays the same
- '+' - line added
- '-' - line removed

**Comment by neomatrix369** [comment]
The line on which this action took place was the last line on HunkHeader, see
```
hunkLines = {java.util.ArrayList@1909}  size = 5
 0 = "@@ -48,4 +48,3 @@"
 1 = "         else:"
 2 = "             prices.append(-1)"
 3 = "     return sum(prices)"
 4 = "-"   <=== error occurred when trying to process this line
```

**Comment by neomatrix369** [comment]
So why is pos only incremented for two types of line changes but not changed when a line is removed? This can be a cause of out of sync in line count or position maintained.

**Comment by julianghionoiu** [comment]
The way I read is is that `pos` tracks the current index in the newLines array, on deletion, we remove from the newLines so, the index does not need to change.

**Comment by neomatrix369** [comment]
On deletion from the newLines if `pos` is not updated, the index is pointing out of bounds? That's how I see it and have been noticing when debugging the specific file that is failing

**Comment by neomatrix369** [comment]
Debugging this issue, I think in this specific case the last empty line is removed some how, because both _oldLines_ and _newLines_ (which is _oldLines_ initially) do not have this empty line saved without he linefeed (empty line) into the file.
