### ISSUE TITLE
Prevent large files from being recorded

### ISSUE THREAD

**Issue by julianghionoiu** [julianghionoiu/dev-sourcecode-record#27]
**Context**
Large files will cause the sourcecode archive to explode in size and the recorder will fail to upload it.

**Solution**

- Refactor to reduce the complexity of the source code selection process (SourceCodeProvider). We should only use CopyFromDirectorySourceCodeProvider and not make references to Git
- The CopyFromDirectorySourceCodeProvider should use a parser for .gitignore and filter files (using java.io.FileFilter) based on that
- The CopyFromDirectorySourceCodeProvider should also have a filter for large files. I think it is safe to assume that if a file is above 2MB it should not be recorded.

**Comment by neomatrix369** [comment]
This one is a bit ambiguous.

> * The CopyFromDirectorySourceCodeProvider should also have a filter for large files. I think it is safe to assume that if a file is above 2MB it should not be recorded.
Are you not going to push such files for changes - or is this a way to detect the concerned file is not a source file.

**Comment by neomatrix369** [comment]
> * The CopyFromDirectorySourceCodeProvider should use a parser for .gitignore and filter files (using java.io.FileFilter) based on that

We have to dodge some strange kind of configs here.

**Comment by julianghionoiu** [comment]
Because the sourcecode upload is very important, we are employing to safety mechanisms:
1. We parse git ignore to remove unneeded stuff. There is already a .gitingore parser in JGit, we should be able to leverage that.

2. We cannot trust the .gitignore. It might be missing, changed or stuff added outside of the ignored areas. For this, we need to exclude large files to ensure that the source code gets at least uploaded.

**Comment by neomatrix369** [comment]
> 2\. We cannot trust the .gitignore. It might be missing, changed or stuff added outside of the ignored areas. For this, we need to exclude large files to ensure that the source code gets at least uploaded.

Now I'm confused, do we or do we not parse the `.gitignore` file?

**Comment by julianghionoiu** [comment]
The confusion is caused by the fact that we currently use two strategies:
- CopyFromDirectorySourceCodeProvider
- CopyFromGitSourceCodeProvider

CopyFromDirectorySourceCodeProvider wraps CopyFromGitSourceCodeProvider. This is the bit that is causing issue.

This tasks is to:
- remove the CopyFromGitSourceCodeProvider
- parse the .gitignore using some classes from JGit
- create a filter for the files that match .gitignore
- create a filter for files that are bigger than 2Mb
